---
ai_pod_name: "ai_pod"
ai_pod_ports:
  - "6333:6333"
  - "3000:8080"
  - "11434:11434"
ai_data_dir: "{{ ansible_facts['user_dir'] }}/.local/share/ai_stack"

ia_stack:
  - name: 'ollama'
    image: 'docker.io/ollama/ollama:latest'
    volumes: ["{{ ai_data_dir }}/ollama:/root/.ollama:Z"]
  - name: 'qdrant'
    image: 'docker.io/qdrant/qdrant:latest'
    volumes: ["{{ ai_data_dir }}/qdrant:/qdrant/storage:Z"]
  - name: 'open-webui'
    image: 'ghcr.io/open-webui/open-webui:main'
    env: { "OLLAMA_BASE_URL": "http://127.0.0.1:11434" }
    volumes: ["{{ ai_data_dir }}/open-webui:/app/backend/data:Z"]
