---
# Configurações de Apps Flatpak
apps_flatpaks:
  - com.google.Chrome
  - com.spotify.Client
  - org.gimp.gimp
  - org.kde.isoimagewriter.desktop
  - org.kde.partitionmanager.desktop
  - org.kde.ark.desktop
  - org.kde.okular.desktop
  - org.kde.kate.desktop