---
# Configurações de Apps Flatpak
apps_flatpaks:
  - com.google.Chrome
  - com.spotify.Client
  - org.gimp.gimp
  - org.kde.isoimagewriter
  - org.kde.partitionmanager
  - org.kde.ark
  - org.kde.okular
  - org.kde.kate
  - org.libreoffice.LibreOffice