---
# 1. Configuração do Brilho do Monitor (I2C)
- name: Instalar pacotes para controle de brilho e utilitários via zypper
  zypper:
    name:
      - ddcutil
      - i2c-tools
      - zsh
    state: present
  become: true

- name: Criar grupo de sistema i2c
  group:
    name: i2c
    state: present
    system: yes
  become: true

- name: Adicionar usuário ao grupo i2c
  user:
    name: "{{ host_user }}"
    groups: i2c
    append: yes
  become: true

- name: Configurar regras de Udev para I2C
  copy:
    dest: /etc/udev/rules.d/99-i2c.rules
    content: "KERNEL==\"i2c-[0-9]*\", GROUP=\"i2c\", MODE=\"0660\""
    owner: root
    group: root
    mode: "0644"
  become: true

- name: Configurar carga do módulo i2c-dev no boot
  copy:
    dest: /etc/modules-load.d/i2c.conf
    content: "i2c-dev"
    owner: root
    group: root
    mode: "0644"
  become: true

